### ISSUE TITLE
explicit_close is a flaky test

### ISSUE THREAD

**Issue by jon-chuang** [tokio-rs/tokio-uring#75]
thread 'explicit_close' panicked at 'Ok(14)', tests/fs_file.rs:152:16

I wonder why

**Comment by Noah-Kennedy** [comment]
@jon-chuang if you see this again, please copy the full backtrace from the panic. As it is, we have no clue what actually went wrong.

**Comment by Noah-Kennedy** [comment]
Got one:
```
failures:

---- explicit_close stdout ----
thread 'explicit_close' panicked at 'Err(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', tests/fs_file.rs:150:16
error: test failed, to rerun pass '--test fs_file'
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:[116](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:116):14
   2: fs_file::assert_invalid_fd
             at ./tests/fs_file.rs:150:16
   3: fs_file::explicit_close::{{closure}}
             at ./tests/fs_file.rs:76:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   5: tokio_uring::runtime::Runtime::block_on::{{closure}}::{{closure}}
             at ./src/runtime.rs:87:21
   6: <tokio_uring::future::PollFn<F> as core::future::future::Future>::poll
             at ./src/future.rs:35:9
   7: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:644:65
   8: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  11: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  12: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  13: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:644:42
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  15: tokio::task::local::LocalSet::with
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:561:9
  16: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:634:9
  17: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:507:18
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:[123](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:123):9
  20: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
  21: tokio::coop::with_budget::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  24: tokio::coop::with_budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  25: tokio::coop::budget
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  26: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
  27: tokio::runtime::basic_scheduler::Context::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  28: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
  29: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  30: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  31: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  32: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  33: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  34: tokio::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  35: tokio_uring::runtime::Runtime::block_on::{{closure}}
             at ./src/runtime.rs:84:13
  36: tokio_uring::driver::Driver::with::{{closure}}
             at ./src/driver/mod.rs:75:37
  37: scoped_tls::ScopedKey<T>::set
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:[137](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:137):9
  38: tokio_uring::driver::Driver::with
             at ./src/driver/mod.rs:75:9
  39: tokio_uring::runtime::Runtime::block_on
             at ./src/runtime.rs:71:9
  40: tokio_uring::start
             at ./src/lib.rs:[144](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:144):5
  41: fs_file::explicit_close
             at ./tests/fs_file.rs:70:5
  42: fs_file::explicit_close::{{closure}}
             at ./tests/fs_file.rs:66:1
  43: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f[172](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:172)67604a5102f57a/library/core/src/ops/function.rs:227:5
  44: core::ops::function::FnOnce::call_once
             at /rustc/9d1b[210](https://github.com/tokio-rs/tokio-uring/runs/5398393106?check_suite_focus=true#step:4:210)6e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    explicit_close

test result: FAILED. 6 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.0
```

**Comment by mzabaluev** [comment]
This is not the only flaky test as of 7d7913c02dc4c633cfff632c2f6f138d53783192:

```
---- drop_open stdout ----
thread 'drop_open' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 46, 46, 46]`', tests/fs_file.rs:92:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: fs_file::drop_open::{{closure}}
             at ./tests/fs_file.rs:92:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: tokio_uring::runtime::Runtime::block_on::{{closure}}::{{closure}}
             at ./src/runtime.rs:87:21
   7: <tokio_uring::future::PollFn<F> as core::future::future::Future>::poll
             at ./src/future.rs:35:9
   8: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:644:65
   9: tokio::coop::with_budget::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  11: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  12: tokio::coop::with_budget
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  13: tokio::coop::budget
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  14: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:644:42
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  16: tokio::task::local::LocalSet::with
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:561:9
  17: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:634:9
  18: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/task/local.rs:507:18
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:123:9
  21: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
  22: tokio::coop::with_budget::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  23: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  24: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  25: tokio::coop::with_budget
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  26: tokio::coop::budget
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  27: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
  28: tokio::runtime::basic_scheduler::Context::enter
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  29: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
  30: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  32: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  33: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  34: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  35: tokio::runtime::Runtime::block_on
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  36: tokio_uring::runtime::Runtime::block_on::{{closure}}
             at ./src/runtime.rs:84:13
  37: tokio_uring::driver::Driver::with::{{closure}}
             at ./src/driver/mod.rs:75:37
  38: scoped_tls::ScopedKey<T>::set
             at /home/mzabaluev/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  39: tokio_uring::driver::Driver::with
             at ./src/driver/mod.rs:75:9
  40: tokio_uring::runtime::Runtime::block_on
             at ./src/runtime.rs:71:9
  41: tokio_uring::start
             at ./src/lib.rs:144:5
  42: fs_file::drop_open
             at ./tests/fs_file.rs:82:5
  43: fs_file::drop_open::{{closure}}
             at ./tests/fs_file.rs:81:1
  44: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  45: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    drop_off_runtime
    drop_open
```

**Comment by FrankReh** [comment]
@Noah-Kennedy 

I propose we close this. The unit tests have been very solid for me the last couple of months but I'm only running on two Linux boxes admittedly. Also ci seems robust lately. Merge #121 has at least a little to do with that.

**Comment by Noah-Kennedy** [comment]
Good idea. We can reopen if it comes up again.
